permissions:
  admin_access: "access_to_admin_page"
  fav_reports: "work_with_favorite_reports"

postgres:
  host: "KRR-SQL-PSGRE00"
  port: 5432
  username: "%PG_LOGIN%"
  password: "%PG_PASSWORD%"
  dbname: "krr-pa-analytics-data"
  sslmode: "disable"

ad_address: "KRR-DC-EU01.europe.mittalco.com:636"
service_id: 15
log_level: "release"
gin_mode: "release"
server_address: "127.0.0.1:5011"
