permissions:
  admin_access: "access_to_admin_page"
  fav_reports: "work_with_favorite_reports"

postgres:
  host: "KRR-SQL-PGNODE00"
  port: 5432
  username: "%PG_USER%"
  password: "%PG_PASSWORD%"
  dbname: "krr-pa-analytics-data"
  sslmode: "disable"

pg_auth:
  host: "KRR-SQL-PGNODE00"
  port: 5432
  username: "%PG_USER%"
  password: "%PG_PASSWORD%"
  dbname: "development"
  sslmode: "disable"

ad_address: "KRR-DC-EU01.europe.mittalco.com:636"
service_id: 15
log_level: "debug"
gin_mode: "debug"
server_address: "127.0.0.1:5011"