permissions:
  admin_access: "access_to_admin_page"
  fav_reports: "work_with_favorite_reports"

mssql:
  server: "KRR-TST-PAHWL02"
  username: "EUROPE\\aadzenzura"
  password: "h)#X2Ubu04Qm6"
  database: "KRR-PA-Reporting"

mssql_auth:
  server: "KRR-TST-PAHWL02" ## Тестовый сервер
  username: "EUROPE\\aadzenzura"
  password: "h)#X2Ubu04Qm6"
  database: "KRR-PA-ACS"

ad_address: "KRR-DC-EU01.europe.mittalco.com:636"
service_id: 15
log_level: "debug"
gin_mode: "debug"
server_address: "127.0.0.1:5010"